# Generated by Django 4.0.3 on 2022-04-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='city',
            new_name='exampleFormControlTextarea1',
        ),
    ]
