# Generated by Django 4.0.3 on 2022-04-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=130)),
                ('contact', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
